services:
  - type: web
    name: web
    env: docker
    dockerfilePath: ./Dockerfile.production
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://api-kasongo.onrender.com
